surveyjs/survey-creator

- src/templates/questionEditors/questioneditortab-general.html
Fixes general tab content (the modal footer border was sitting at the top basically, so looked broken)
> Added .row div wrapper as per bootstrap docs

- src/adorners/title-editor.ts
https://github.com/surveyjs/editor/issues/400
Leverages a canvas' context's `measureText` method to calculate the appropriate length of a text input, rather than setting the inputs size which is not effective on non-monospaced fonts.
> Issue #400 Wiggling text input resolved using canvas measure text.

- src/localization/french.ts
I added a few missing french localization strings after getting an answer form support ticket T2150.
> Missing strings in french localization

- package.json
- src/translation.ts
- tests/translationtest.ts
This PR cleans up the translation module:
- Use PapaParse, a library dedicated to parsing CSVs.
- Use modern JS / TS since it is compiled to a target JS version anyway.
- Fixes #777
> External CSV parser

- packages/survey-creator-core/src/components/question.scss
- packages/survey-creator-core/src/components/question.ts
see https://github.com/surveyjs/survey-creator/issues/2172
> v2: DnD: while dragging selected element the "selection"(orange border) should go to the shortcut and moved to element after drag 

- packages/survey-creator-core/src/components/tabs/translation-plugin.ts
- packages/survey-creator-core/src/components/tabs/translation.ts
- packages/survey-creator-core/src/creator-base.ts
- packages/survey-creator-core/tests/tabs/translation.tests.ts
- packages/survey-creator/src/creator-base.ts
- packages/survey-creator/src/tabs/translation.ts
- packages/survey-creator/tests/translationtest.ts
https://github.com/surveyjs/survey-creator/issues/1863
> Is there a way to hide specific fields in the translation tab and/or disable the 'show all pages' dropdown? #1863

- packages/survey-creator-core/src/creator-base.ts
- packages/survey-creator-core/tests/creator-base.tests.ts
> resolve #2268 - keep Expand Property Grid action in the end of toolbar

- .vscode/settings.json
- packages/survey-creator-core/src/creator-base.ts
- packages/survey-creator-core/tests/creator-base.tests.ts
see https://github.com/surveyjs/survey-creator/issues/2846
didn't create unit test because drag drop emulation doesn't make any sense in unit tests
> V2: Support onDragDropAllow event

- packages/survey-creator-core/src/creator-base.ts
I had a hard time figuring out how to upload files to a server (the examples were a bit outdated). The docs didn't specify the function signature for `options.callback`, so I added some details to make it easier for the next person :)
> Clarify docs in onUploadFile event

- packages/survey-creator-core/src/components/simulator.ts
- packages/survey-creator/src/components/simulator.ts
I tried importing this library into a next.js project (with SSR) and this `window` reference causes an issue. 
```
error - ReferenceError: window is not defined
at Module../src/components/simulator.ts (/node_modules/survey-creator-core/survey-creator-core.js:2949:27)
```
I see this issue has been brought up before: https://surveyjs.answerdesk.io/ticket/details/t8983/referenceerror-window-is-not-defined-while-importing-latest-survey-creator-react-version
The fix seems pretty simple—just changed the `!!window` to `typeof window !== "undefined"`. I was able to modify this file locally and test it and confirmed it worked.
> Bug - `window` reference causes issue in `next.js`

- packages/survey-creator-core/src/components/string-editor.ts
- packages/survey-creator-core/tests/string-editor.tests.ts
> #3568 Safari: Shift-Tab does not work after string editor click

- packages/survey-creator-core/src/property-grid/matrices.ts
- packages/survey-creator-core/tests/property-grid/property-grid.tests.ts
> #3642 Property Grid - The detail view and the choice's edit button remain visible even if a choice item has no properties

- packages/survey-creator-core/src/property-grid/matrices.ts
see https://github.com/surveyjs/survey-creator/issues/3797
tests in the library's commit
> Choices Property Group - Screen Reader doesn't announce the expanded/collapsed state for the choice detail panel when focusing the Edit button 

- packages/survey-creator-angular/src/string-editor.component.html
- packages/survey-creator-angular/src/string-editor.component.ts
- packages/survey-creator-core/src/components/string-editor.ts
- packages/survey-creator-knockout/src/string-editor.html
- packages/survey-creator-knockout/src/string-editor.ts
- packages/survey-creator-react/src/StringEditor.tsx
- testCafe/designer/string-editor.ts
Fixes #4183
Unfortunately this issue fix **can not be tested automatically** with Jest or TestCafe.
You can test it manually.
Build and run SurveyCreator.
Open Chrome console and execute this code:
```
document.addEventListener('copy', function(e){
e.clipboardData.setData('text/html', '<span>s\nd</span>');
e.clipboardData.setData('text/plain', 's d');
e.preventDefault(); // default behaviour is to copy any selected text
});
```
Click on any question title. Press `Crtl-C` (the clipboard data will be filled in code you entered in console).
Press `Ctrl-V` and see the pasted text.
If you see "s d" with whitespace between, all is ok.
If you see "sd" _without_ whitespaces between, it is going wrong and works as not expected.
> #4183 Question Title Editor removes whitespaces when copying the text from a MS 365 Word Desktop

- packages/survey-creator-core/src/components/string-editor.ts
- packages/survey-creator-core/tests/string-editor.tests.ts
> #4412 When the creator.inplaceEditForValues option is enabled, the None and Other item text is not correctly updated

- packages/survey-creator-core/src/localization/french.ts
In English localization: 
https://github.com/surveyjs/survey-creator/blob/master/packages/survey-creator-core/src/localization/english.ts#L149
```
addNewQuestion: "Add Question",
```
Based on a user inquiry at https://surveyjs.answerdesk.io/internal/ticket/details/T14174#236c5536-80fe-455c-ba4e-4a39545a8396.
> Fix the addNewQuestion string

- packages/survey-creator-core/src/components/tabs/theme-builder.ts
- packages/survey-creator-core/src/creator-base.ts
- packages/survey-creator-core/tests/tabs/theme-builder.tests.ts
Fixed #4762 - Not all theme's settings saved;
Fixed https://github.com/surveyjs/private-tasks/issues/310 - cover is not saved;
Work for https://surveyjs.answerdesk.io/internal/ticket/details/T15010 - don't use creator.isModified flag for theme builder
> Not all theme settings is saved/restored, wrong modification state flag

- packages/survey-creator-core/src/components/string-editor.ts
- packages/survey-creator-react/src/PageNavigator.tsx
- packages/survey-creator-react/src/StringEditor.tsx
> Fixed #4897 - Warnings when scrolling a design surface in StrictMode - An attempt to set a property "errorText" of a disposed object "base"

- packages/survey-creator-core/src/components/tabs/theme-builder.ts
- packages/survey-creator-core/src/components/tabs/theme-plugin.ts
- packages/survey-creator-core/src/components/tabs/themes.ts
- packages/survey-creator-core/src/creator-base.ts
- packages/survey-creator-core/tests/tabs/integration.tests.ts
- packages/survey-creator-core/tests/tabs/theme-builder.tests.ts
- Combine Survey and Theme Saving - Introduce an option to activate the Save button regardless of whether a survey layout or theme receives changes #4894
- Support custom themes variations (light/dark, panelless/panels)
> Theme builder API enchancements 1

- packages/survey-creator-core/src/components/header/logo-image.ts
- packages/survey-creator-core/tests/tabs/designer.test.ts
> Fixed #4881 - Setting an overriding property on the survey logo property doesn't disable the logo upload in the editor

- packages/survey-creator-core/src/components/string-editor.ts
- packages/survey-creator-core/src/creator-events-api.ts
- packages/survey-creator-core/tests/string-editor.tests.ts
> #5275 The `onItemValueAdded` event is not raised when a new matrix row is added by pressing the Enter key on the design surface

- packages/survey-creator-core/src/components/question-rating.ts
- packages/survey-creator-core/tests/components.tests.ts
> Rating Scale - The Label Alignment option remains active even though Min and Max value labels are unspecified

- packages/survey-creator-core/src/creator-events-api.ts
Fixes https://github.com/surveyjs/survey-creator/issues/5655
> Update the `onModified` event description

- packages/survey-creator-core/src/creator-base.ts
- packages/survey-creator-core/tests/dragdrop.tests.ts
> Fixed #5670 - onModified with options.type: "ADDED_FROM_TOOLBOX" isn't raised if a survey element is dragged from the Toolbox

- packages/survey-creator-core/src/components/page.scss
- packages/survey-creator-core/src/components/question.scss
- packages/survey-creator-core/src/components/row.scss
- packages/survey-creator-core/src/components/string-editor.scss
- packages/survey-creator-core/src/components/toolbox/toolbox-tool.scss
- packages/survey-creator-core/src/property-grid-theme/blocks/spg-question.scss
- packages/survey-creator-core/src/property-grid-theme/blocks/spg-table.scss
- packages/survey-creator-core/src/property-grid-theme/blocks/spg-theme-builder.scss
- packages/survey-creator-core/src/utils/context-button.scss
Sass's behavior for declarations that appear after nested rules will be changing to match the behavior specified by CSS in an upcoming version. To keep the existing behavior, move the declaration above the nested rule.
> fix Deprecation Warning Sass

- packages/survey-creator-core/src/components/matrix-cell.scss
> Fixed #5697 - Multi-Select Matrix - The Radiogroup column choices popup editor displays a gap on the right side

- packages/survey-creator-core/src/components/page-navigator/page-navigator-item.scss
> Fixed #5714 - Page Navigator is blinking when page names are long

- .eslintrc.json
- packages/survey-creator-core/src/creator-base.ts
- packages/survey-creator-core/tests/creator-undo-redo.tests.ts
> Fixed #5783 - Weird drag behaviour to empty survey in Safari - stop undo/redo transaction on banned drop

- .github/workflows/ci.yml
The current azure pipelines are very hard to read for developers not familiar with them.
Also they are very slow and do a lot.
This PR adds an extra workflow for PRs that just runs eslint via github actions. Note: since this is an open source repo the CI minutes for this are free afaik.
> chore(ci): add separate github action workflow that runs eslint

- packages/survey-creator-core/src/components/question-image.ts
> Fixed #5982 - An Image question doesn't display a validation error when replacing an existing image and an image upload error occurs

- packages/survey-creator-core/src/toolbox.ts
Fixes https://github.com/surveyjs/survey-creator/issues/5999
> Toolbox: Publish the `getSubitem()` method

- functionalTests/designer/surface.ts
- packages/survey-creator-core/src/components/action-container-view-model.ts
- packages/survey-creator-core/src/components/page.ts
- packages/survey-creator-core/src/components/question.ts
> #6233 Expand/Collapse Questions - Double-clicking a title text within an inplace editor collapses or expands a question

- packages/survey-creator-core/src/creator-events-api.ts
- packages/survey-creator-core/src/plugins/undo-redo/undo-redo-controller.ts
> #6339 Rename paramaters in the `onBeforeUndo` and `onBeforeRedo` events

- packages/survey-creator-core/src/components/page.ts
Fixes #6555
Fixed https://github.com/surveyjs/private-tasks/issues/452
> #6555 Empty page's placeholder doesn't collapse animated.

- packages/survey-creator-core/src/components/toolbox/toolbox-tool.scss
> #6681 Toolbox subitems: A bottom subitem's shadow overflows the container

- packages/survey-creator-core/src/components/toolbox/toolbox-tool.scss
> #6701 Toolbox. Submenu button doesn't align correctly (UI scaling less 100 per cent)

- packages/survey-creator-js/src/index.ts
During SSR the window object is not available.
While I realize this is probably not supported in the creator anyway, it is still good to check for the existence of `window` before accessing it.
Since it is only a very small change I think it can be part of the core.
> fix: access global window safely

- packages/survey-creator-angular/src/toolbox/toolbox-item.component.html
- packages/survey-creator-knockout/src/toolbox/toolbox-item.html
- packages/survey-creator-react/src/toolbox/ToolboxItem.tsx
- packages/survey-creator-vue/src/toolbox/ToolboxItem.vue
Ensures there's always a `title` attribute for `svg` icons which are given the `img` `role`.
@dmitry-kurmanov @dk981234
> Fix a11y title for svg icons within toolbox

- packages/survey-creator-core/src/creator-base.ts
- packages/survey-creator-core/tests/creator-base-v1.tests.ts
> onElementAllowOperations - A question can still be removed regardless the `options.allowDelete = false` parameter
