gulpfile.js, package.json, packagetemplate.json, src/dragdrophelper.ts, src/editor.ts, src/objectEditor.ts, src/objectProperty.ts, src/objectVerbs.ts, src/pagesEditor.ts, src/propertyEditors/propertyMatrixDropdownColumnsEditor.ts, src/propertyEditors/propertyRestfullEditor.ts, src/propertyEditors/propertyTextItemsEditor.ts, src/propertyEditors/propertyTriggersEditor.ts, src/propertyEditors/propertyValidatorsEditor.ts, src/surveyHelper.ts, src/surveyObjects.ts, src/textWorker.ts, src/undoredo.ts, tests/ObjectEditorTestedClasses.ts, tests/SurveyEditorTests.ts, tests/propertyEditorsTests.ts, tests/surveyObjectsTests.ts, tests/undoredoTests.ts, typings.json, webpack.config.js
- added source-map-loader into package.json
- survey-knockout-bootstrap => survey-knockout
=> webpack + es2015 modules:

src/localization/italian.ts
Add translations on Italian language localization
=> Add translations on Italian language localization

src/editor.ts
Just thought I'd add two more supported properties in the options object. I had a look at updating the docs but couldn't work out how to do it (happy to update with some guidance). Cheers.
=> Updated constructor docblock

src/localization/german.ts
... feel free to amend if necessary since I took the English as base for my translation without knowing the UI.
=> added german.ts translation file

src/localization/polish.ts
Importing editorLocalization.ts instead defining object in polish.ts
=> Importing editorLocalization.ts

src/localization/french.ts
=> Update French localization

src/localization/persian.ts
completed Persian translations
=> change translations

src/localization/english.ts
Recently we were asked to remove unused localization strings
I removed a set
We need to check it
=> Feature: remove unused strings

packages/survey-creator-core/src/property-grid/condition-survey.ts, packages/survey-creator-core/tests/property-grid/condition-survey.tests.ts
Update condition editor layout and localization.
=> Feature 1190

packages/survey-creator-core/src/property-grid-theme/blocks/spg-panel.scss, packages/survey-creator-core/src/property-grid-theme/blocks/spg-table.scss, packages/survey-creator-core/src/property-grid-theme/property-grid.ts
-Fix matrixdynamic editor in Property Grid
=> Work for #1108: fix styles for matrix in property grid

packages/survey-creator-core/src/property-grid/index.ts
=> Fix for example choices and depends on properties

packages/survey-creator-core/src/components/item-value.scss, packages/survey-creator-core/src/components/page.scss, packages/survey-creator-core/src/components/question.scss, packages/survey-creator-core/src/components/tabs/designer.scss, packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/src/survey-designer-theme/blocks/sd-panel.scss, packages/survey-creator-core/src/survey-designer-theme/blocks/sd-row.scss, packages/survey-creator-knockout/src/components/question-dropdown.html
- Fix dropdown designer component in Knockout
- Fix styles for item adorners in Knockout
- Fix designer survey width when json is empty
=> Work for #1203

packages/survey-creator-core/src/property-grid/index.ts, packages/survey-creator-core/tests/property-grid/property-grid.tests.ts
Reverts surveyjs/survey-creator#1347
=> Revert "Feature/issue 1346 value editor in detail"

packages/survey-creator-core/src/questionconverter.ts, packages/survey-creator-core/tests/question-converter.tests.ts
(cherry picked from commit a8ad7b2674f83fe3db6efe77409c92be943f2c4d)
=> closes #1398 fix property name

packages/survey-creator-knockout/src/components/page.html, packages/survey-creator-react/src/components/Page.tsx
=> Render page id in designer, #1528

packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/src/settings.ts
Restrict moving question between pages in V2 https://surveyjs.answerdesk.io/ticket/details/T7387
=> work for the https://github.com/surveyjs/survey-creator/issues/1559

packages/survey-creator-core/src/property-grid/matrices.ts, testCafe/designer/drag-drop.js
Allow to drag&drop columns and pages in property editors, V2
=> work for the #1563

packages/survey-creator-core/src/property-grid/matrices.ts
Property Grid Matrix Dynamic Columns AllowDragDrop
=> work for the #1623

packages/survey-creator-knockout/src/entries/index.ts, packages/survey-creator-react/src/entries/index.ts
https://surveyjs.answerdesk.io/ticket/details/t7636/some-issue-on-surveyjs-creator-v2
=> Add export for

packages/survey-creator-core/src/property-grid-theme/blocks/spg-table.scss
Fix columns headers in property grid
=> Fix for #1733

packages/survey-creator-core/src/components/tabs/designer.ts, packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/tests/creator-base.tests.ts, packages/survey-creator-knockout/src/components/creator.ts, packages/survey-creator-knockout/src/creator.ts, packages/survey-creator-react/src/SurveyCreator.tsx
CreatorV2: keyboard shortcuts (commands)
=> work for the #1843

packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/tests/creator-base.tests.ts
V2: Custom Widget based on Panel doesn't work properly (T7833)
=> fixed #1906

packages/survey-creator/testCafe/tests/drag_and_drop.js
CV1: Cannot Delete Ranking Question
=> work for the https://github.com/surveyjs/survey-creator/issues/1908

packages/survey-creator-core/src/components/question.ts
V2: Drag Drop: Dynamic Panel Drop Style
=> work for the #1894

packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/tests/creator-base.tests.ts
=> custom widget add question titles and adding errors

packages/survey-creator-core/src/components/string-editor.ts, packages/survey-creator-knockout/index.html, packages/survey-creator-knockout/src/components/string-editor.ts, packages/survey-creator-react/src/components/StringEditor.tsx, testCafe/designer/string-editor.ts
=> prevent string editor unfocus for question items

packages/survey-creator-core/src/components/string-editor.scss
=> do not hide focused string editor green frame on hover

packages/survey-creator-core/src/components/item-value.ts, packages/survey-creator-core/src/components/toolbox/toolbox-tool.ts, packages/survey-creator-core/src/utils/dragOrClickHelper.ts, packages/survey-creator-knockout/src/components/image-item-value.html, packages/survey-creator-knockout/src/components/item-value.html, packages/survey-creator-react/src/components/ImageItemValueWrapper.tsx, packages/survey-creator-react/src/components/ItemValueWrapper.tsx
see https://github.com/surveyjs/survey-creator/issues/2065
=> CV2: DnD: choices(include imagepicker) and ranking items should be draggable by whole item.

packages/survey-creator-core/src/components/tabs/logic-ui.scss
=> hide logic separator

packages/survey-creator-core/src/toolbox.ts, packages/survey-creator-core/src/utils/dragOrClickHelper.ts, testCafe/designer/drag-drop.ts
see https://github.com/surveyjs/survey-creator/issues/2162
=> V2: Allow dragging from the toolbox responsivity popup

packages/survey-creator-core/src/components/tabs/designer.scss
=> remove close property grid button from non-mobile

packages/survey-creator-core/src/components/page.scss, packages/survey-creator-core/src/responsivity.scss
resolved #2199
also question top padding fixed
=> center "add question"

packages/survey-creator-core/src/components/question.scss
see https://github.com/surveyjs/survey-creator/issues/2170
=> v2: DnD: added corresponding "question type icon" to dragged element shortcut

packages/survey-creator-core/src/components/item-value.ts, packages/survey-creator-core/tests/components.tests.ts
=> CV2: Do not start dragging choices on editing text

packages/survey-creator-react/src/components/RowWrapper.tsx, packages/survey-creator-react/src/components/tabs/Designer.tsx
see https://github.com/surveyjs/survey-creator/issues/2210
=> CV2 React Warnings (DnD new page key) 

packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/tests/creator-base-v1.tests.ts, packages/survey-creator-core/tests/creator-base.tests.ts, testCafe/designer/drag-drop.ts, testCafe/json/json.ts
https://github.com/surveyjs/survey-creator/issues/2239
=> Creator V2: survey logo has different position in creator and customer survey #2239

devops-pull-requests.yml
add TESTCAFE_DASHBOARD_AUTHENTICATION_TOKEN
=> Update devops-pull-requests.yml for Azure Pipelines

packages/survey-creator-core/src/components/string-editor.scss, packages/survey-creator-core/src/components/string-editor.ts, testCafe/designer/string-editor.ts
=> fixed #2281 - check isRequired in stringeditor

packages/survey-creator-core/src/components/tabs/designer.scss, packages/survey-creator-core/src/creator-base.ts, testCafe/designer/hovers.ts
=> #2361 - fix page padding and hover delay

packages/survey-creator-core/src/components/page.ts, packages/survey-creator-core/src/components/tabs/designer-plugin.ts, packages/survey-creator-core/src/components/tabs/designer.ts, packages/survey-creator-core/tests/tabs/designer.test.ts, packages/survey-creator-knockout/src/components/tabs/designer.html, packages/survey-creator-react/src/components/tabs/Designer.tsx, testCafe/designer/select-context.ts
=> #2297 - reset selection and select survey on designer click

packages/survey-creator-core/src/question-editor/definition.ts, packages/survey-creator-core/tests/property-grid/property-grid.tests.ts, packages/survey-creator/src/questionEditors/questionEditorDefinition.ts, packages/survey-creator/tests/propertyEditors/propertyEditorsTests.ts
=> fixed "other section" unit test

packages/survey-creator-core/src/components/string-editor.ts, packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/tests/string-editor.tests.ts, testCafe/designer/string-editor.ts
=> #2390 - support inplaceEditForValues

packages/survey-creator-core/src/components/question.ts, packages/survey-creator-knockout/src/components/question-widget.html, packages/survey-creator-knockout/src/components/question.html, packages/survey-creator-react/src/adorners/QuestionHeader.tsx, testCafe/designer/drag-drop.ts
see https://github.com/surveyjs/survey-creator/issues/2319
=> DnD: SurveyElement: "click or drag"

packages/survey-creator-core/src/property-grid/index.ts, packages/survey-creator-core/tests/property-grid/property-grid.tests.ts, visualRegressionTests/tests/designer/toolbox.ts
=> fixed #2425 - readonly choices in property grid

packages/survey-creator-core/src/components/item-value.scss
=> fixed #2476 - item adorners invisible width

packages/survey-creator-core/src/components/item-value.scss
see https://github.com/surveyjs/survey-creator/issues/2533
=> Choices/ItemValues: multicolumn layout broken style

packages/survey-creator-core/src/components/action-container-view-model.ts, packages/survey-creator-core/tests/creator-responsivity-manager.test.ts
=> fixed #2547 - question settings visibility

packages/survey-creator-knockout/src/components/item-value.html, testCafe/designer/string-editor.ts
=> fixed #2422 - click near item

packages/survey-creator-core/src/components/side-bar/side-bar.scss, testCafe/designer/responsiveness.ts
=> fixed #2548 - sidebar shadow click - fixed z-index

packages/survey-creator-core/src/utils/dragOrClickHelper.ts
see https://github.com/surveyjs/survey-library/issues/3823
=> Click on drag-area on touch devices set question to "--draggable" state forever

packages/survey-creator-core/src/creator-responsivity-manager.ts
see https://github.com/surveyjs/survey-creator/issues/2456
=> Responsivity Manager: detect retina

packages/survey-creator-core/src/components/page-navigator/page-navigator-item.scss, testCafe/designer/hovers.ts
=> #2558 page navigator hover z-index

packages/survey-creator-core/src/components/side-bar/side-bar.scss, testCafe/designer/responsiveness.ts
=> #2559 - adaptivity: sidebar max size

packages/survey-creator-core/src/components/item-value.scss
=> fixed #2603 - vue build and surve warning (flex-end)

packages/survey-creator-core/src/components/string-editor.ts, packages/survey-creator-knockout/src/components/string-editor.ts, packages/survey-creator-react/src/components/StringEditor.tsx, testCafe/designer/string-editor.ts
=> #2640 - allow edit markdown in string editor

packages/survey-creator-core/src/property-grid-theme/blocks/spg-checkbox.scss, packages/survey-creator-core/src/property-grid-theme/property-grid.ts
=> #2644 - draw checkbox as svg in markup

packages/survey-creator-core/src/components/string-editor.ts, packages/survey-creator-knockout/src/components/string-editor.ts, packages/survey-creator-react/src/components/StringEditor.tsx, testCafe/designer/inplace-editors.ts, testCafe/designer/string-editor.ts
=> #2675 - V2: Improve usability of inline edit

packages/survey-creator-react/src/adorners/Page.tsx, testCafe/designer/hovers.ts
=> #2685 - Page hover blinking on title mouse move - REACT

docs/Migrate-from-V1-to-V2.md, packages/survey-creator-knockout/README.md, packages/survey-creator-react/README.md
=> Update READMEs and What's New with info about core package

packages/survey-creator-core/src/components/item-value.scss
=> #2733 - Ranking inactive item should be gray

packages/survey-creator-react/src/tabs/Designer.tsx
see https://github.com/surveyjs/survey-creator/issues/2754
=> React: Perfomace: Implemented rendered pages cache

packages/survey-creator-react/src/tabs/Designer.tsx, testCafe/designer/clear-survey.ts
Also see [this PR](https://github.com/surveyjs/survey-library/pull/4102) in the library
=> Small fix and new test for #2765

packages/survey-creator-core/src/property-grid/matrices.ts
see https://github.com/surveyjs/survey-creator/issues/2709
=> V2: Allow to reorder triggers in the property grid

packages/survey-creator-core/src/components/toolbox/toolbox-tool.scss
=> Work for  #2629: all dropdown actions have pressed state

packages/survey-creator-core/src/questionconverter.ts, packages/survey-creator-core/src/toolbox.ts, packages/survey-creator-core/tests/question-converter.tests.ts
=> #2851 - Set default images after convert question to Image or Image Picker

packages/survey-creator-react/src/ItemValueWrapper.tsx
=> PR: Dropdown: Move new Items (React only)

packages/survey-creator-knockout/src/tabs/designer.html, packages/survey-creator-react/src/tabs/Designer.tsx
=> V2: could not drag a new question on text "The survey is empty. ..."

packages/survey-creator-core/src/components/toolbox/toolbox-tool.ts
see https://github.com/surveyjs/survey-creator/issues/2957
=> DND: From Toolbox: Shortcut text

packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/tests/creator-base.tests.ts
=> #2974 - Do not process Del key when focus is inside DIV with content editable

packages/survey-creator-core/src/creator-responsivity-manager.ts
=> #2991 - Fix Creator Responsivity on Retina and 4K displays

packages/survey-creator-core/src/components/string-editor.scss, packages/survey-creator-react/testCafe/testcafe.html, testCafe/designer/string-editor.ts
=> #3017 - Fix string editor issue in Safari

packages/survey-creator-core/src/localization/english.ts
=> Fix a couple texts in English localization

docs/property-grid.md
=> Add "multiplevalues" to types in the Property Grid help topic

packages/survey-creator-core/src/components/tabs/logic.scss
https://surveyjs.answerdesk.io/ticket/details/T9599
=> fix styles for safari

packages/survey-creator-core/src/components/tabbed-menu/tabbed-menu-item.scss
=> #3077 - Different Creator tab paddings in inline or singlepage modes

packages/survey-creator-core/src/components/toolbox/toolbox.scss
=> #3084 - Simple Toolbox categories CSS fixes

packages/survey-creator-core/src/questionconverter.ts, packages/survey-creator-core/tests/question-converter.tests.ts
=> #3088 - Converting Matrix Dropdown to matrix Singlechoice or vise-versa causes caption issues

packages/survey-creator-core/tests/creator-empty.tests.ts
=> onModified event not firing after json property is set to empty fixed #3283

packages/survey-creator-core/tests/creator-base.tests.ts, packages/survey-creator-core/tests/property-grid/object-selector.tests.ts, packages/survey-creator-core/tests/property-grid/property-grid-viewmodel.tests.ts, packages/survey-creator-core/tests/tabs/test.tests.ts
(cherry picked from commit 1edd027dfd7d82ff034901703a5aa97fac07ca25)
=> rename listModel method

packages/survey-creator-knockout/src/side-bar/side-bar.html, packages/survey-creator-react/src/SideBar.tsx, testCafe/designer/side-bar.ts
see https://github.com/surveyjs/survey-creator/issues/3310
=> Close Property Grid by click the outside (Tablet size) 

packages/survey-creator-core/src/plugins/undo-redo/undo-redo-manager.ts, packages/survey-creator-core/tests/creator-base.tests.ts
=> #3318 - onModified event confuses newValue and oldValue on UNDO

packages/survey-creator-react/src/StringEditor.tsx, testCafe/designer/string-editor.ts
=> #3325 - Replace string editor callback with events

packages/survey-creator-core/src/plugins/undo-redo/undo-redo-controller.ts, packages/survey-creator-core/tests/creator-base.tests.ts
=> #3336 - Redo does not work with some events

packages/survey-creator-react/src/ImageItemValueWrapper.tsx, testCafe/designer/surface.ts
=> #3347 - React: Image Picker wrong styling after item delete

packages/survey-creator-react/src/ImageItemValueWrapper.tsx, testCafe/designer/surface.ts
=> #3375 - Image Picker Issue when deleting the image and not able to add again

packages/survey-creator-core/src/components/string-editor.scss
=> #3380 - Text input issue (safari)

docs/property-grid.md
=> Property Grid doc: Describe onExecuteExpression and fix case in custom property names

packages/survey-creator-core/src/components/item-value.ts, packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/tests/question-editors.tests.ts, testCafe/designer/string-editor.ts
=> #3480 Focus should not come to inactive fields, such as Select All, None, and Other.

packages/survey-creator-core/tests/property-grid/object-selector.tests.ts
=> #3473 Matrix Dropdown / Dynamic - Columns are not accessible from the Property Grid selector

packages/survey-creator-angular/src/string-editor.component.html, packages/survey-creator-core/src/components/string-editor.ts, packages/survey-creator-core/tests/string-editor.tests.ts, testCafe/designer/string-editor.ts
=> #3518 Inserting a ready-made list of answers. By ctrl + V, the list of answers is filled, starting with the focused one.

packages/survey-creator-core/src/components/creator.scss
=> #3420 Creator Fonts (mac os)

packages/survey-creator-core/src/components/tabs/test-plugin.ts, packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/src/creator-options.ts, packages/survey-creator-core/src/localization/english.ts, packages/survey-creator-core/tests/tabs/test.tests.ts, testCafe/preview/toolbar.ts, visualRegressionTests/tests/designer/test-tab.ts
=> #3613 #3614 The Mobile preview switcher tooltip always shows 'Landscape'

packages/survey-creator-core/package.json, packages/survey-creator-core/src/components/tabs/json-editor-ace.ts, testCafe/json/json.ts
=> #3653 The JSON Editor search box doesn't work because ext-searchbox.js is not loaded

packages/survey-creator-core/package.json, packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/src/entries/survey-creator-core.fontless.scss, packages/survey-creator-core/src/variables.scss, packages/survey-creator-core/webpack.config.js
see https://github.com/surveyjs/survey-creator/issues/3654
=> Use local fonts for the defaultV2 theme

packages/survey-creator-angular/src/adorners/item-value.component.html, packages/survey-creator-knockout/src/adorners/item-value.html, packages/survey-creator-react/src/ItemValueWrapper.tsx
=> PR : Accessibility Issue for a Required Checkbox: Ensures every ARIA input field has an accessible name 

packages/survey-creator-core/src/components/question.ts
=> Accessibility Issue: The screenreader doesn't announce the Required option state 

packages/survey-creator-angular/src/tabs/designer/designer-survey.component.html, packages/survey-creator-knockout/src/tabs/designer.html, packages/survey-creator-react/src/tabs/Designer.tsx, testCafe/designer/survey-width.ts
=> Creator survey width and adaptivity

packages/survey-creator-core/src/components/string-editor.ts, packages/survey-creator-core/tests/string-editor.tests.ts
=> #3668 The maxLength property doesn't work when pasting the text to an inplace element editor

packages/survey-creator-core/src/components/string-editor.ts, packages/survey-creator-core/tests/string-editor.tests.ts
=> #3670 Creator. Drop-down issue with keyboard navigation

packages/survey-creator-core/src/property-grid-theme/blocks/spg-dropdown.scss
=> #3671 SAFARI - Creator. Property Grid. Text alignment

packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/src/property-grid/index.ts, packages/survey-creator-core/src/property-grid/matrices.ts, packages/survey-creator-core/tests/property-grid/property-grid.tests.ts
=> #3644 The onSetPropertyEditorOptions - options.showTextView option doesn't hide but disables the Fast Entry editor

packages/survey-creator/package.json, packages/survey-creator/src/adorners/image-items.ts, packages/survey-creator/src/adorners/item-editor.ts, packages/survey-creator/src/adorners/select-items-editor.ts, packages/survey-creator/vendor/knockout-sortable.js, packages/survey-creator/vendor/sortable.js
https://github.com/surveyjs/survey-creator/issues/3727
=> Survey Creator V1 - The Cannot read properties of null (reading 'dispatchEvent') exception is thrown when reordering choices in the Property Grid

packages/survey-creator-core/src/components/item-value.ts, packages/survey-creator-core/src/components/string-editor.ts, packages/survey-creator-core/tests/string-editor.tests.ts, packages/survey-creator-knockout/src/adorners/image-item-value.html, testCafe/designer/string-editor.ts
=> #3787 Image Picker - Updating an item caption throws an error and creates an unnecessary image picker item

docs/uri.json
Please check https://surveyjs.io/survey-creator/documentation/build-component-questions redirect definition
(first task from https://github.com/surveyjs/service/issues/751 )
=> Redirect component question doc

packages/survey-creator-core/src/components/question-rating.ts, packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/src/localization/english.ts, packages/survey-creator-core/tests/components.tests.ts, packages/survey-creator-core/tests/creator-base.tests.ts
=> #3782 SelectBase questions contains "item#" when opening an existing survey

packages/survey-creator-core/src/creator-base.ts
From https://github.com/surveyjs/survey-creator/issues/3801
=> Mark properties as Depricated; update description.

packages/survey-creator-core/src/components/action-container-view-model.ts, packages/survey-creator-core/src/components/side-bar/side-bar-model.ts, packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/tests/creator-tester.ts, testCafe/designer/side-bar.ts
=> #3793 Survey Creator in Mobile mode - Tab Navigation works incorrectly when the Property Grid overlays the design area

packages/survey-creator-core/src/components/item-value.ts, packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/src/creator-settings.ts, packages/survey-creator-core/src/property-grid/index.ts, packages/survey-creator-core/tests/components.tests.ts
=> #3923 Modify event to prevent users from adding or removing choices from a design surface.

packages/survey-creator-core/src/property-grid/matrices.ts, packages/survey-creator-core/tests/property-grid/property-grid.tests.ts
=> #4015 Fast entry for rating does not work

packages/survey-creator-core/src/creator-base.ts
=> Describe `toolboxLocation` and `sidebarLocation`

packages/survey-creator-core/src/question-editor/definition.ts, packages/survey-creator-core/tests/property-grid/property-grid.tests.ts
=> #4098 Multi-Select Matrix: Rating Scale columns do not display controls that change the rate type to "stars" or "smileys"

packages/survey-creator-core/src/localization/english.ts
=> #4144 Rating Question - The rateType property values are not localizable

packages/survey-creator-core/src/components/question-rating.ts, packages/survey-creator-core/src/property-grid/matrices.ts, packages/survey-creator-core/src/utils/utils.ts, packages/survey-creator-core/tests/property-grid/property-grid.tests.ts
=> #4145 Rating Scale in matrix - console error on rateCount change

packages/survey-creator-core/src/components/question-rating.ts, packages/survey-creator-core/tests/components.tests.ts
=> #4170 Rating Scale - Impossible to disable the add and remove options for rate items

packages/survey-creator-angular/README.md, packages/survey-creator-knockout/README.md, packages/survey-creator-react/README.md
=> Add build instructions for the Angular, React, and Knockout packages

packages/survey-creator-core/src/question-editor/definition.ts
see ttps://github.com/surveyjs/survey-creator/issues/4414
=> CREATOR: PR: Ranking Question - The selectToRankEnabled setting is not available in a Property Grid

packages/survey-creator-core/src/components/tabs/theme-custom-questions/font-settings.ts, packages/survey-creator-core/src/components/tabs/theme.ts, packages/survey-creator-core/src/localization/english.ts, packages/survey-creator-core/tests/tabs/theme-builder.tests.ts
fixed  https://github.com/surveyjs/private-tasks/issues/262
=> add placeholder color editor

docs/get-started-angular.md
https://surveyjs.io/survey-creator/documentation/get-started-angular
Fixed a typo in the code:
=> Update the Get Started code for Angular

packages/survey-creator-core/src/components/action-container-view-model.ts, testCafe/designer/side-bar.ts
=> #4541 Mobile: Do not focus name property on showing Property Grid

packages/survey-creator-core/src/components/question-rating.ts, packages/survey-creator-core/tests/components.tests.ts
=> #4606 Rating Smiles allows to set Max rate value on disabled button

packages/survey-creator-core/src/localization/german.ts
"Art des Tarifs" and "Anzahl der Raten"  sounds in german like buying a washing machine on installments.
I have also deleted a few automatically generated translations that I think are ok from the list below.
=> Updated german translations

packages/survey-creator-core/src/components/tabs/test.ts, packages/survey-creator-core/tests/creator-base.tests.ts
=> Fixed #4686 - A custom theme specified via the creator.theme is not applied to a survey unless the Theme Tab is activated

packages/survey-creator-core/src/property-grid/matrices.ts, packages/survey-creator-core/tests/property-grid/color.tests.ts, packages/survey-creator-core/tests/property-grid/file.tests.ts, packages/survey-creator-core/tests/property-grid/overriding-property.tests.ts, packages/survey-creator-core/tests/property-grid/property-grid-matrices.tests.ts, packages/survey-creator-core/tests/property-grid/property-grid-v1.tests.ts, packages/survey-creator-core/tests/property-grid/property-grid.base.ts, packages/survey-creator-core/tests/property-grid/property-grid.tests.ts, packages/survey-creator-core/tests/property-grid/reseteditor.tests.ts
=> Validation Error is reset and Choice Values are updated incorreclty

packages/survey-creator-core/src/components/tabs/theme-builder.ts, packages/survey-creator-core/tests/tabs/theme-builder.tests.ts
=> Fixed #4705 - Theme settings are reset when switching to another creator tab

packages/survey-creator-core/src/survey-helper.ts, packages/survey-creator-core/tests/creator-base.tests.ts
=> Fixed #4740 - onElementDeleting: options.elementType contains cryptic numbers

packages/survey-creator-core/src/components/tabs/theme-builder.ts, packages/survey-creator-core/tests/tabs/theme-builder.tests.ts
=> Fixed #4744 - Theme Editor - A Background image is not reset when changing a theme

packages/survey-creator-angular/src/tabs/preview/test.component.html, packages/survey-creator-angular/src/tabs/theme/theme.component.html, packages/survey-creator-core/src/components/tabs/test.ts, packages/survey-creator-core/src/components/tabs/theme-builder.ts, packages/survey-creator-knockout/src/tabs/test.html, packages/survey-creator-knockout/src/tabs/theme.html, packages/survey-creator-react/src/tabs/Preview.tsx, packages/survey-creator-react/src/tabs/Theme.tsx, testCafe/preview/survey-results.ts
=> Fixed #4715 - Survey Results appear broken on mobile

packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/tests/tabs/test.tests.ts
=> Fixed #4756 - Theme is not applied if set when "Preview" tab already active

package.json, packages/survey-creator-angular/package.json, packages/survey-creator-knockout/package.json, packages/survey-creator-react/package.json, packages/survey-creator-vue/package.json
see https://github.com/surveyjs/private-tasks/issues/313
=> PR: Blinking Tests: Creator: Update Testcafe 

packages/survey-creator-core/src/survey-elements.ts
see https://github.com/surveyjs/survey-creator/issues/4644
=> PR: The surface scrolling stops working after dragging items from the toolbox (iPad)

packages/survey-creator-core/src/components/tabs/theme-builder.ts, packages/survey-creator-core/tests/tabs/theme-builder.tests.ts
=> Fixed #4804 - Background image is reset for custom theme after reset theme action

packages/survey-creator-core/src/components/string-editor.ts, packages/survey-creator-core/tests/string-editor.tests.ts
=> Paste strings to the items issue.

testCafe/property-grid/choices.ts
=> Fixed #4830 - Image Picker - Non-existing items appear on a design surface

packages/survey-creator-react/src/ItemValueWrapper.tsx, packages/survey-creator-react/src/adorners/QuestionDropdown.tsx, testCafe/designer/inplace-editors.ts
=> #4856 Choice inplace editing doesn't work when adding more choices

packages/survey-creator-core/src/components/tabs/theme-plugin.ts, packages/survey-creator-core/src/localization/english.ts, packages/survey-creator-core/tests/tabs/theme-builder.tests.ts
=> Implemented #4866 - The Save button is not available within the Themes Tab when the isAutoSave option is disabled

packages/survey-creator-core/src/components/tabs/theme-builder.ts, packages/survey-creator-core/tests/tabs/theme-builder.tests.ts
=> Fixed #4870 - Themes Tab - The themeModified event is not raised and the Save button remains disabled when modifying the Background or Accent Color

testCafe/designer/drag-drop.ts
see https://github.com/surveyjs/survey-creator/issues/4888
=> PR (CREATOR) (Functional Test): Imagepicker item looses controls after dragging 

packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/src/survey-elements.ts
see https://github.com/surveyjs/survey-library/issues/7336
Fixes https://github.com/surveyjs/survey-creator/issues/4885
=> PR: CREATOR: Change onDragDropAllow options

packages/survey-creator-core/src/components/tabs/theme-plugin.ts, packages/survey-creator-core/tests/tabs/theme-builder.tests.ts
=> Fixed #4848 - Loaded theme is reset due to property changing - theme should be exported with a new name

docs/survey-localization-translate-surveys-to-different-languages.md
=> Localization docs: Create a section for information about custom locales

docs/overview.md
Update 
https://surveyjs.io/survey-creator/documentation/overview
Modern, customizable UI themes > [CSS-based Theme Editor](https://surveyjs.io/survey-creator/documentation/theme-editor)
=> Survey Creator Overview - Update Feature List

packages/survey-creator-angular/src/tabs/preview/survey-results-row.component.html, packages/survey-creator-core/src/components/results.ts, packages/survey-creator-knockout/src/results-table-row.html, packages/survey-creator-react/src/Results.tsx, packages/survey-creator-vue/src/tabs/preview/SurveyResultsRow.vue, testCafe/preview/survey-results.ts
=> Resolved #4920 - The Survey Results table displays unformatted question titles

packages/survey-creator-angular/src/question.component.html, packages/survey-creator-knockout/src/adorners/question.html, packages/survey-creator-react/src/adorners/Question.tsx, packages/survey-creator-vue/src/adorners/QuestionBase.vue, testCafe/designer/creator.ts
=> Fixed#4952 - Looks like a hover state is a useless step (keyboard navigation)

packages/survey-creator-react/src/toolbox/ToolboxItem.tsx, packages/survey-creator-vue/src/toolbox/ToolboxTool.vue, testCafe/designer/toolbox.ts
=> #4992 Survey Creator for React - 'undefined' appears within svc-toolbox__tool elements

packages/survey-creator-core/src/toolbox.ts, packages/survey-creator-core/tests/toolbox.tests.ts
=> #5003 Toolbox - undefined appears within a custom widget's toolbox item class list

packages/survey-creator-core/src/components/tabs/theme-builder.ts, packages/survey-creator-core/src/components/tabs/theme-custom-questions/boxshadow-settings.ts, packages/survey-creator-core/tests/tabs/theme-builder.tests.ts
see https://github.com/surveyjs/survey-library/issues/7498
=> PR: CREATOR: Animation: Focus and Selected State 

packages/survey-creator-core/src/components/tabs/theme-plugin.ts, packages/survey-creator-core/tests/tabs/theme-builder.tests.ts
=> Fixed #5029 - Preview is not updated after the theme's loading

packages/survey-creator-core/src/localization/german.ts
This PR updates some translations in the theme editor which are either unnatural or incorrect
=> Update german localization

packages/survey-creator-core/src/components/string-editor.scss
=> Fixed #5098 - A long Question Description is not wrapped and overlaps a question's area

docs/get-started-angular.md, docs/get-started-knockout-jquery.md, docs/get-started-react.md, docs/get-started-vue.md
Fixes https://github.com/surveyjs/service/issues/1862
=> Describe how to verify survey JSON schemas on a server

.vscode/settings.json, docs/customize-survey-creation-process.md, packages/survey-creator-core/src/components/action-container-view-model.ts, packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/src/creator-events-api.ts, packages/survey-creator-core/src/question-editor/definition.ts, packages/survey-creator-core/tests/creator-base.tests.ts
=> Implemented #5046 - Add an option to specify adorner actions visibility

packages/survey-creator-core/src/components/question-image.ts, packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/tests/components.tests.ts
=> Fixed #5124 - The creator.onOpenFileChooser event is not raised when a user activates a file upload window for an Image question

packages/survey-creator-core/src/components/tabs/theme-builder.ts, packages/survey-creator-core/tests/tabs/theme-builder.tests.ts
https://github.com/surveyjs/survey-creator/pull/5059/commits/c85c45558b20f8cfbcea0981020e3a59614e8ec5
=> revert commit 

packages/survey-creator-core/src/components/image-item-value.scss, testCafe/designer/surface.ts
=> Fixed #5195 - Image Picker - An item cannot be deleted by clicking a Delete button on a design surface

packages/survey-creator-core/src/components/simulator.scss
see the https://github.com/surveyjs/survey-creator/issues/5189
=> PR: Message Box Issue 

packages/survey-creator-core/src/components/tabs/designer.ts, packages/survey-creator-core/src/components/tabs/theme-custom-questions/color-settings.ts, packages/survey-creator-core/src/components/tabs/theme-custom-questions/font-settings.ts, packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/src/property-grid/index.ts, packages/survey-creator-core/src/property-grid/matrices.ts, packages/survey-creator-core/tests/creator-base.tests.ts, packages/survey-creator-core/tests/property-grid/property-grid.tests.ts
=> Fixed #5160 - The options.allow = false within the creator.onPageAdding event doesn't prevent a page from being added

packages/survey-creator-core/src/components/toolbox/toolbox.scss
=> Fixed#5251 - Toolbox's left padding disappeared somewhere

packages/survey-creator-core/src/survey-elements.ts, packages/survey-creator-core/tests/dragdrop-elements.tests.ts
=> Fixed #5291 - creator.onQuestionAdded event is not fired on dragging an item from a toolbox

packages/survey-creator-core/src/components/question.ts, packages/survey-creator-core/tests/creator-toolbox.tests.ts
=> Fixed #4940 - convertTo question menu incorrect for custom question type (contains duplicated items)

packages/survey-creator-core/src/components/string-editor.ts
=> #5353 Pasting to the list issue.

packages/survey-creator-core/src/components/page.scss, packages/survey-creator-core/src/components/page.ts, packages/survey-creator-core/tests/page-adorner.tests.ts
=> Fixed #5367 - A drop indicator appears at an incorrect position when the Add Question button is hidden

packages/survey-creator-angular/src/tabs/designer/designer-pages.component.html, packages/survey-creator-core/src/components/tabs/designer.ts, packages/survey-creator-knockout/src/tabs/designer.html, packages/survey-creator-react/src/tabs/Designer.tsx, packages/survey-creator-vue/src/tabs/designer/Designer.vue, testCafe/designer/drag-drop.ts
=> Fixed #5366 - In ByPage survey edit mode, a new page is automatically created when a question is dropped to the end of the current page

packages/survey-creator-core/src/components/tabs/test.ts, packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/src/creator-settings.ts, packages/survey-creator-core/tests/tabs/test.tests.ts
=> Implemented #5380 - Introduce an option to hide the Survey Results section within the Preview tab

packages/survey-creator-core/src/localization/english.ts
Fix https://github.com/surveyjs/survey-creator/issues/5378
=> Update the `contentMode` hint

packages/survey-creator-knockout/src/question-widget.html
=> Fixed #5384 - [jQuery] Drag and Drop Adorner Doesn't Appear when a custom widget is registered

packages/survey-creator-core/src/editorLocalization.ts, packages/survey-creator-core/tests/tabs/translation.tests.ts
=> Fixed #5388 - Translation Tab - Row text is split after a period in multiple lines in a translation tab

packages/survey-creator-core/src/utils/layout.scss, testCafe/designer/surface.ts
Fixed https://github.com/surveyjs/service/issues/2073
=> Survey Creator demos: A shade on the design surface can be scrolled when Property Grid is open

packages/survey-creator-core/src/localization/english.ts, packages/survey-creator-core/src/question-editor/definition.ts
https://github.com/surveyjs/survey-library/issues/8094
=> Signature placeholder in read-only mode 

packages/survey-creator-core/src/components/simulator.scss, testCafe/preview/survey.ts
=> #5415 Dynamic panel (tab view). Menu should be closed by clicking outside

packages/survey-creator-core/src/components/string-editor.ts, packages/survey-creator-core/tests/string-editor.tests.ts, packages/survey-creator-core/tests/tabs/designer.test.ts
=> #5419 Typing in a long text is buggy in firefox

packages/survey-creator-angular/src/adorners/image-item-value.component.html, packages/survey-creator-core/src/components/image-item-value.ts, packages/survey-creator-knockout/src/adorners/image-item-value.html, packages/survey-creator-react/src/ImageItemValueWrapper.tsx, packages/survey-creator-vue/src/adorners/ImageItemValue.vue
work for the https://github.com/surveyjs/survey-creator/issues/5449
=> PR: Image Picker - A screen reader doesn't announce the Add New item button

packages/survey-creator-core/src/components/simulator.ts, packages/survey-creator-core/src/components/tabs/test-plugin.ts, packages/survey-creator-core/tests/tabs/test.tests.ts
=> Implemented #5461 - Device Selector Drop-Down Menu - Introduce an API which would allow developers to add/remove/reorder available device options

packages/survey-creator-core/src/components/question.scss
work for the https://github.com/surveyjs/survey-creator/issues/5466
=> PR: Fix drag Shortcut styles

packages/survey-creator-core/src/components/tabs/preview.ts, packages/survey-creator-core/tests/tabs/test.tests.ts
=> Fixed #2329 - Survey Creator - The options.allow = false within onNavigateToUrl doesn't work in a creator preview

packages/survey-creator-core/src/localization/english.ts, packages/survey-creator-core/tests/tabs/test.tests.ts
Fixes https://github.com/surveyjs/survey-creator/issues/5677
=> Add a hint for the "Column count" property

packages/survey-creator-core/src/creator-settings.ts, packages/survey-creator-core/tests/creator-base.tests.ts, packages/survey-creator-core/tests/survey-text-worker.test.ts, packages/survey-creator-core/tests/tabs/json-editor.tests.ts, testCafe/json/json.ts
=> Fixed #5678 - JSON Editor: Use 2 instead of 3 spaces for indentation

packages/survey-creator-core/src/components/action-container-view-model.ts, testCafe/designer/surface.ts
=> Fixed #5684 - Expand/collapse panels/questions and lazy rendering issue

packages/survey-creator-core/src/components/string-editor.ts, packages/survey-creator-core/tests/string-editor.tests.ts
=> #5732 Enable matrix column and row limit for columns and rows added via a design surface

packages/survey-creator-core/src/localization/english.ts
Fixes https://github.com/surveyjs/survey-library/issues/8672
=> File Upload: Add a hint for the `allowImagesPreview` property

packages/survey-creator-core/src/components/tabs/logic-ui.scss, packages/survey-creator-core/src/components/tabs/logic.scss
work for the https://github.com/surveyjs/survey-creator/issues/5791
=> PR: Wrong expression items' text color on hover + wrong title color

packages/survey-creator-core/src/components/action-container-view-model.ts, packages/survey-creator-core/src/components/page.scss, packages/survey-creator-core/src/components/page.ts, testCafe/designer/surface.ts
=> #5668 Page toolbar responsivity issue.

packages/survey-creator-core/src/components/row.ts, packages/survey-creator-core/src/survey-elements.ts, testCafe/designer/drag-drop.ts
=> Form Builder Drag-Drop: Can't see a drop indicator for a row (top/bottom)

packages/survey-creator-core/src/components/action-container-view-model.ts, packages/survey-creator-core/tests/survey-element-action-container.tests.ts
=> #5846 Probably we need to use `canShrink` property instead of `disableShrink.

packages/survey-creator-core/src/components/tabs/theme-model.ts, packages/survey-creator-core/tests/tabs/theme-tab-plugin.tests.ts
=> Fixed #5831 - The ThemeTabPlugin.onThemePropertyChanged event is not raised when updating a theme's custom property value

packages/survey-creator-angular/src/toolbox/adaptive-toolbox.component.html, packages/survey-creator-knockout/src/toolbox/adaptive-toolbox.html, packages/survey-creator-react/src/toolbox/AdaptiveToolbox.tsx, packages/survey-creator-vue/src/toolbox/AdaptiveToolbox.vue
=> Fixed #5783 - Weird drag behaviour to empty survey in Safari

packages/survey-creator-core/src/components/question.ts, packages/survey-creator-core/tests/question-adorner.tests.ts
=> #5859 Rating question conversion in subitems

packages/survey-creator-core/src/localization/japanese.ts
**Description:**
I made some improvements to the Japanese localization due to awkward phrasing and inconsistencies. 
The key changes are:
- Fixed unnatural Japanese translations for better clarity and readability.
- Improved overall coherence of the Japanese text to enhance user experience.
Please review the changes and let me know if any further modifications are needed.
=> Fixed translation errors in Japanese localization

packages/survey-creator-core/src/components/question.ts, packages/survey-creator-core/src/toolbox.ts, packages/survey-creator-core/tests/creator-base.tests.ts, packages/survey-creator-core/tests/question-adorner.tests.ts, packages/survey-creator-core/tests/survey-element-action-container.tests.ts, packages/survey-creator-core/tests/toolbox.tests.ts
=> A subitem configuration / mask settings are not copied when converting a question from the default input type to a sub-item

packages/survey-creator-core/src/components/page.ts, packages/survey-creator-core/tests/page-adorner.tests.ts
=> #5932 The unexpected Settings action appears on hovering over the Add Question button

packages/survey-creator-core/src/components/action-container-view-model.ts, packages/survey-creator-core/src/components/question.ts, packages/survey-creator-core/src/components/string-editor.scss
https://github.com/surveyjs/survey-creator/issues/5956
=> PR: Adorner actions appear after a delay 

packages/survey-creator-core/src/components/side-bar/side-bar-header-model.ts, packages/survey-creator-core/src/components/side-bar/side-bar-model.ts
=> The `creator.sidebar.toolbar` property is `undefined` in v1.12.5

packages/survey-creator-core/src/localization/finnish.ts
Made translations more consistent, corrected typos and added some missing translations
=> Updates for finnish.ts

packages/survey-creator-core/src/components/action-container-view-model.ts, packages/survey-creator-core/src/components/page.ts, packages/survey-creator-core/src/components/question.ts, packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/src/creator-events-api.ts, packages/survey-creator-core/src/creator-options.ts, packages/survey-creator-core/src/expand-collapse-manager.ts, packages/survey-creator-core/tests/question-adorner.tests.ts, packages/survey-creator-core/tests/tabs/designer.test.ts
=> #6038 Implement expand-collapse API

packages/survey-creator-core/src/components/toolbox/toolbox-animation.scss, packages/survey-creator-core/src/components/toolbox/toolbox.scss
=> #6064 Broken toolbox styles after drag from

packages/survey-creator-core/src/components/action-container-view-model.ts, packages/survey-creator-core/tests/question-adorner.tests.ts
=> On using creator.onElementGetExpandCollapseState panels & dynamic panels do not show all elements on expanding

functionalTests/designer/surface.ts, packages/survey-creator-core/src/components/question.scss
work for the https://github.com/surveyjs/survey-creator/issues/6138
=> PR: A question is not selected on a design surface if a user clicks a question's input field area

functionalTests/designer/surface.ts, packages/survey-creator-core/src/components/question.scss
https://github.com/surveyjs/survey-creator/issues/6138
=> PR: TextArea: A question is not selected on a design surface if a user clicks a question's input field area 

packages/survey-creator-core/src/components/question.scss
work for the https://github.com/surveyjs/private-tasks/issues/407
=> PR: Creator v2.0: Design Surface: Dragged Question

packages/survey-creator-core/src/components/tabs/logic.scss, packages/survey-creator-core/src/property-grid-theme/blocks/spg-color-editor.scss, packages/survey-creator-core/src/property-grid-theme/blocks/spg-dropdown.scss, packages/survey-creator-core/src/property-grid-theme/blocks/spg-input.scss, packages/survey-creator-core/src/property-grid-theme/blocks/spg-panel.scss, packages/survey-creator-core/src/property-grid-theme/blocks/spg-question.scss, packages/survey-creator-core/src/property-grid-theme/blocks/spg-theme-builder.scss, packages/survey-creator-core/src/property-grid-theme/property-grid.ts, packages/survey-creator-core/src/property-grid/matrices.ts, packages/survey-creator-core/src/property-grid/search-manager.ts, packages/survey-creator-core/src/utils/actions.ts
Fixed surveyjs/private-tasks#402
=> Creator V2. Scaling property grid editors

packages/survey-creator-core/src/components/tabs/theme-plugin.ts, packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/tests/tabs/theme-tab-plugin.tests.ts
=> Hide theme settings button for property grid with side tabs navigation

packages/survey-creator-core/src/components/link-value.scss, packages/survey-creator-core/src/creator-theme/action-button.scss, packages/survey-creator-core/src/property-grid-theme/blocks/spg-matrixdynamic.scss, packages/survey-creator-core/src/property-grid-theme/blocks/spg-question.scss
=> fixed pg drag icon sizes

packages/survey-creator-core/src/custom-questions/question-spin-editor.ts
=> #6243 Fix infinite scaling increase/decrease on fast clicks

packages/survey-creator-core/src/components/question.ts, packages/survey-creator-core/src/toolbox.ts, packages/survey-creator-core/tests/question-adorner.tests.ts
=> #6259 Duplicated item in subitems list

packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/src/creator-options.ts, packages/survey-creator-core/tests/tabs/designer.test.ts
=> #6261 Add settng to collapse elements on designer by default after JSON loading

packages/survey-creator-core/src/components/scroll.ts
=> #6288 Smooth scroll incorrectly works with new scrollbar

packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/src/creator-events-api.ts, packages/survey-creator-core/src/creator-options.ts
=> #6342 Rename the `onPropertyGridShowModal` event and properties related to the Logic tab

packages/survey-creator-core/src/creator-base.ts
=> #6325 Set tabResponsivenessMode property to 'icons' by default

packages/survey-creator-core/src/utils/layout.scss
=> #6474 Scaling issues. Forgot some buttons in the menu.

functionalTests/designer/surface.ts, packages/survey-creator-core/src/components/page.scss
=> #6490 Page is not selected by click on the header

functionalTests/designer/question-wrapper.ts, packages/survey-creator-core/src/components/action-container-view-model.ts, packages/survey-creator-core/src/localization/english.ts
=> #6487 Missing tooltips on page, panel, and question expand/collapse

functionalTests/designer/drag-drop.ts, packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/src/property-grid/matrices.ts, packages/survey-creator-react/src/tabs/Designer.tsx
=> Page dragging issue. Placeholder page disappears.

functionalTests/designer/surface.ts, packages/survey-creator-core/src/components/tabs/designer-plugin.ts, packages/survey-creator-core/tests/creator-base-1.tests.ts
=> #6538 Survey Settings button is invisible when Property grid is shown

packages/survey-creator-core/creator-themes-import.js, packages/survey-creator-core/src/creator-theme/creator-theme-model.ts
work for the https://github.com/surveyjs/service/issues/2819
=> PR: V2 - Creator Themes are missing

packages/survey-creator-core/src/components/page.ts, packages/survey-creator-core/src/creator-base.ts
Fixes #6570
Fixes https://github.com/surveyjs/private-tasks/issues/458
=> #6570 Page expand/collapse issue on the mobile

packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/src/utils/utils.ts
=> #6551 Keyboard doesn't appear or useless title selection (iPad).

packages/survey-creator-core/src/components/question.ts, packages/survey-creator-core/src/creator-base.ts
=> Turn off the "collapse pages on drag start" option for questions dragging

packages/survey-creator-core/src/components/string-editor.ts, packages/survey-creator-core/tests/string-editor.tests.ts
=> Choice Inplace Editor allows a batch creating of more than the specified number of items (`creator.maximumChoicesCount`)

packages/survey-creator-core/src/components/question.ts, packages/survey-creator-core/tests/question-adorner.tests.ts
=> #6635 The removeSubItems function doesn't remove corresponding input types in a property grid

packages/survey-creator-core/src/components/string-editor.ts, packages/survey-creator-core/tests/string-editor.tests.ts
=> #6653 Inplace Editor - A line break character `\n` appears when removing the title or description

packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/tests/creator-base-2.tests.ts, packages/survey-creator-core/tests/tabs/theme-tab-plugin.tests.ts
=> Theme Editor: It's impossible to switch from advanced to basic header after changing some settings of advanced header

packages/survey-creator-core/src/components/question.ts, packages/survey-creator-core/tests/question-adorner.tests.ts
=> #6692 Toolbox subitems: Subitem dropdown contains incorrect subitems

packages/survey-creator-core/src/components/list.scss, packages/survey-creator-core/src/components/toolbox/toolbox.scss, packages/survey-creator-react/package.json
=> #6700 Toolbox and dropdown list separators disappear due to small UI scaling (Safari).

packages/survey-creator-core/src/components/tabs/designer-plugin.ts, packages/survey-creator-core/src/components/tabs/theme-plugin.ts, packages/survey-creator-core/src/property-grid/index.ts, packages/survey-creator-core/src/question-editor/properties.ts, packages/survey-creator-core/tests/property-grid/property-grid.tests.ts
=> Property Grid - Introduce an API for specifying icons for custom property grid categories

packages/survey-creator-core/src/components/tabs/theme-model.ts, packages/survey-creator-core/src/components/tabs/theme-plugin.ts, packages/survey-creator-core/tests/tabs/theme-header-model.tests.ts, packages/survey-creator-core/tests/tabs/theme-model-property-grid.tests.ts, packages/survey-creator-core/tests/tabs/theme-model.tests.ts, packages/survey-creator-core/tests/tabs/theme-tab-plugin.tests.ts
=> Check whole theme is stored in theme JSON (for library theme model only)

packages/survey-creator-core/src/components/question-image.ts, packages/survey-creator-core/tests/components.tests.ts
=> Uncaught TypeError: Cannot read properties of undefined (reading 'imageLink')

packages/survey-creator-react/src/TabbedMenu.tsx
=> Fix a11y role

packages/survey-creator-core/src/survey-helper.ts, packages/survey-creator-core/tests/property-grid/property-grid.tests.ts
=> The rowsVisibleIf expression is applied within the Default Value dialog

packages/survey-creator-angular/src/page-element-content.component.ts, packages/survey-creator-angular/src/question-element-content.component.ts
=> #6894 [Angular 18] Performance Issues when navigating through a large survey-2

packages/survey-creator-core/src/components/page-navigator/page-navigator.ts, packages/survey-creator-core/tests/creator-base-1.tests.ts
=> Page Navigator - One page is selected and Page 1 is always focused

accessibilityTests/designer.spec.ts, packages/survey-creator-core/src/localization/english.ts, packages/survey-creator-core/src/toolbox.ts
=> #6953 Toolbox compact: Buttons must have discernible text

e2e/string-editor.spec.ts, packages/survey-creator-core/src/components/string-editor.ts
=> #7002 It is possible to paste into title text that has bigger length than allowed

packages/survey-creator-core/src/components/page-navigator/page-navigator.scss
=> #7034 Creator - Tiny actions appear when using a creator in NextJS with Tailwind

packages/survey-creator-core/src/components/string-editor.ts, packages/survey-creator-core/tests/string-editor.tests.ts
=> #7032 A character counter displays a wrong current number of characters within a design surface

packages/survey-creator-core/src/editorLocalization.ts, packages/survey-creator-core/tests/creator-base-2.tests.ts
=> Trial banner doesn't display the message in non-English locales

packages/survey-creator-core/src/components/tabs/designer-plugin.ts, packages/survey-creator-core/tests/creator-base-1.tests.ts
=> #7062 Display the Save action within a footer toolbar when the auto-save is disabled

packages/survey-creator-core/src/components/question.ts, packages/survey-creator-core/tests/question-adorner.tests.ts
=> #7098 Toolbox - A sub-item dropdown menu displays a wrong selected item

packages/survey-creator-core/src/localization/german.ts
Fixes https://github.com/surveyjs/survey-creator/issues/7136
=> Update German dictionary

packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/tests/creator-base-1.tests.ts, packages/survey-creator-core/tests/creator-base-2.tests.ts
=> Introduce an option to disable inplace editing for form string elements

packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/src/creator-events-api.ts, packages/survey-creator-core/tests/creator-base-2.tests.ts
=> Work for #7148 - Introduce an API to disable inplace editing for survey UI elements

packages/survey-creator-core/src/creator-base.ts, packages/survey-creator-core/src/creator-responsivity-manager.ts, packages/survey-creator-core/tests/creator-base-1.tests.ts, packages/survey-creator-core/tests/creator-responsivity-manager.test.ts
=> #7153 showSidebar does not work on first render

packages/survey-creator-core/src/localization/english.ts
https://github.com/surveyjs/survey-library/issues/10399
=> PR: Creator: Slider - Introduce an option to render value and text in custom labels

packages/survey-creator-core/src/components/question.ts
=> [React Strict Mode] It is possible to add more than the maximum number of specified choices using the Add Choice adorner action
